# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
# Update packages with $ pre-commit autoupdate
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    -   id: trailing-whitespace
        exclude: ^docs/_images/  # don't touch svg files
    -   id: end-of-file-fixer
    -   id: check-toml
    -   id: check-ast
    -   id: check-merge-conflict
    -   id: debug-statements
    -   id: mixed-line-ending
        args: ['--fix=lf']
-   repo: https://github.com/ikamensh/flynt/
    rev: '0.69'
    hooks:
    -   id: flynt
-   repo: https://github.com/asottile/pyupgrade
    rev: v2.30.0
    hooks:
    -   id: pyupgrade
        args: ['--py37-plus']
-   repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
    -   id: isort
-   repo: https://github.com/psf/black
    rev: 21.12b0
    hooks:
      - id: black
        language_version: python3
-   repo: https://github.com/asottile/blacken-docs
    rev: v1.12.0
    hooks:
    -   id: blacken-docs
        additional_dependencies: [black>=21.9b0]
-   repo: https://github.com/pycqa/flake8
    rev: '4.0.1'  # pick a git hash / tag to point to
    hooks:
    -   id: flake8
        additional_dependencies: [flake8-colors, flake8-bugbear, flake8-comprehensions]
-   repo: https://github.com/pycqa/pydocstyle
    rev: 6.1.1  # pick a git hash / tag to point to
    hooks:
    -   id: pydocstyle
        files: ^src/billiards/
        additional_dependencies: ["toml"]  # config in pyproject.toml file
-   repo: https://github.com/pycqa/doc8
    rev: 0.10.1
    hooks:
    -   id: doc8
        files: ^docs/
